<?php
/**
 * Created by PhpStorm.
 * User: ELL
 * Date: 24/11/2017
 * Time: 10.12
 */

namespace backend\controllers\master;
use backend\models\Agama;
use Yii;
use yii\base\Exception;
use yii\helpers\Url;


use backend\controllers\BaseController;

class AgamaController extends BaseController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
    public function  actionIndex(){
        if(!parent::isLogin()){
            return $this->redirect(Url::toRoute('site/login'));
        }

        $data = Agama::find()->all();
        $sesi = $this->activeUser;
        $isAdmin = $this->isAdmin();

        $params = [
            'data' => $data,
            'sesi' => $sesi,
            'isAdmin' => $isAdmin
        ];
        if (Yii::$app->request->isPost) {
            return $this->renderPartial('index.tpl', $params);
        } else {
            return $this->render('index.tpl', $params);
        }

    }
    public  function  actionForm(){
        $id = Yii::$app->request->post('id', 0);
        if ($id) {
            $data = Agama::findOne($id);
        } else {
            $data = new Agama();
        }
        $params = [
            'data' => $data,
        ];
        return $this->renderPartial('form.tpl', $params);
    }
    public  function actionSave(){
        $id = Yii::$app->request->post('id', 0);
        if ($id) {
            $data =Agama::findOne($id);
        }else{
            $data= new Agama();
        }
        $data->nama=Yii::$app->request->post('nama', '');
        try{
            $data->save();
            return "
            <div class='alert alert-success'>Data berhasil disimpan</div>
            <script> reloadData(); closeModal(1500); </script>";
        }catch (Exception $e){
            return "
            <div class='alert alert-danger'>Data gagal disimpan</div>
            <script> reloadData(); closeModal(1500); </script>";
        }
    }
    public function  actionDelete(){
        $id = Yii::$app->request->post('id', 0);
        $data = Agama::findOne($id);
        try {
            $data->delete();
            return "
            <div class='alert alert-success'>Data berhasil dihapus</div>
            <script> reloadData(); closeModal(1500); </script>";
        } catch (Exception $e) {
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal dihapus</div>";
        }
    }

}