<?php
/**
 * Created by PhpStorm.
 * User: ELL
 * Date: 20/12/2017
 * Time: 12.39
 */

namespace backend\controllers\operator;

use backend\models\LaporAduan;
use Yii;
use yii\base\Exception;
use yii\helpers\Url;
use backend\controllers\BaseController;

class LaporAduanController extends BaseController
{
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        if(!parent::isLogin()){
            return $this->redirect(Url::toRoute('site/login'));
        }
        $params['data']=LaporAduan::find()->all();
        if (Yii::$app->request->isPost) {
            return $this->renderPartial('index.tpl', $params);
        } else {
            return $this->render('index.tpl', $params);
        }
    }

    public function  actionVerifikasi(){
        $id = Yii::$app->request->post('id', 0);
        $data = LaporAduan::findOne($id);
        $data->status='diverifikasi';
        try {
            $data->save();
            return "
            <div class='alert alert-success'>Data berhasil diverifikasi</div>
            <script> reloadData(); closeModal(1500); </script>";
        } catch (Exception $e) {
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal diverifikasi</div>";
        }
    }

    public function  actionTolak(){
        $id = Yii::$app->request->post('id', 0);
        $data = LaporAduan::findOne($id);
        $data->status='ditolak';
        try {
            $data->save();
            return "
            <div class='alert alert-success'>Data berhasil ditolak</div>
            <script> reloadData(); closeModal(1500); </script>";
        } catch (Exception $e) {
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal ditolak</div>";
        }
    }


}