<?php
/**
 * Created by PhpStorm.
 * User: ELL
 * Date: 18/12/2017
 * Time: 08.41
 */

namespace backend\controllers\operator;

use backend\models\Mitra;
use backend\models\User;
use Yii;
use yii\base\Exception;
use yii\helpers\Url;
use backend\controllers\BaseController;

class MitraController extends BaseController
{
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    public function actionIndex(){
        if(!parent::isLogin()){
            return $this->redirect(Url::toRoute('site/login'));
        }
        $params['data']=Mitra::find()->all();


        if (Yii::$app->request->isPost) {
            return $this->renderPartial('index.tpl', $params);
        } else {
            return $this->render('index.tpl', $params);
        }
    }

    public function actionForm(){
        $id=Yii::$app->request->post('id',0);
        if($id){
            $data=Mitra::findOne($id);
        }else{
            $data= new Mitra();
        }
        $params=[
            'data'=>$data,
        ];
        return $this->renderPartial('form.tpl', $params);

    }
    public  function actionSave(){
        $id=Yii::$app->request->post('id',0);
        if($id){
            $data=Mitra::findOne($id);
        }else{
            $data= new Mitra();
        }
        $dataUser= new User();
        $dataUser->username=Yii::$app->request->post('username','');
        $password=Yii::$app->request->post('password','');
        $password2=Yii::$app->request->post('password2','');
        $namaMitra=Yii::$app->request->post('nama_mitra','');
        $alamat=Yii::$app->request->post('alamat','');
        $no_telp=Yii::$app->request->post('no_telp','');
        $email=Yii::$app->request->post('email','');


        if (strlen($password) < 8) {
            return "
                <div class='alert alert-danger'>Terjadi kesalahan! Password minimal 8 karakter</div>";
        } else if ($password != $password2) {
            return "
                <div class='alert alert-danger'>Terjadi kesalahan! Konfirmasi password tidak sesuai</div>";
        }
        $dataUser->password = sha1($password);
        $dataUser->roles_id=8;

        try{
            if($dataUser->save()){
                $data->nama_mitra=$namaMitra;
                $data->alamat=$alamat;
                $data->no_telp=$no_telp;
                $data->email=$email;
                $data->users_id=$dataUser->id;
                $data->save();
                return "
            <div class='alert alert-success'>Data berhasil disimpan</div>
            <script> reloadData(); closeModal(1500); </script>";
            }
        }catch (Exception $e){
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal disimpan</div>";
        }
    }

    public  function actionDelete(){
        $id = Yii::$app->request->post('id', 0);
        $data = Mitra::findOne($id);

        try {
            $data->delete();
            return "
            <div class='alert alert-success'>Data berhasil dihapus</div>
            <script> reloadData(); closeModal(1500); </script>";
        } catch (Exception $e) {
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal dihapus</div>";
        }

    }

}


