<?php
/**
 * Created by PhpStorm.
 * User: ELL
 * Date: 14/01/2018
 * Time: 18.52
 */

namespace backend\controllers\operator;
use backend\controllers\BaseController;
use backend\models\Pengumuman;
use Yii;
use yii\base\Exception;
use yii\helpers\Url;

class PengumumanController extends BaseController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
    public function  actionIndex(){
        if(!parent::isLogin()){
            return $this->redirect(Url::toRoute('site/login'));
        }

        $data = Pengumuman::find()->all();
        $sesi = $this->activeUser;
        $isAdmin = $this->isAdmin();

        $params = [
            'data' => $data,
            'sesi' => $sesi,
            'isAdmin' => $isAdmin
        ];
        if (Yii::$app->request->isPost) {
            return $this->renderPartial('index.tpl', $params);
        } else {
            return $this->render('index.tpl', $params);
        }

    }
    public  function  actionForm(){
        $id = Yii::$app->request->post('id', 0);
        if ($id) {
            $data = Pengumuman::findOne($id);
        } else {
            $data = new Pengumuman();
        }
        $params = [
            'data' => $data,
        ];
        return $this->renderPartial('form.tpl', $params);
    }
    public  function actionSave(){
        $id = Yii::$app->request->post('id', 0);
        if ($id) {
            $data =Pengumuman::findOne($id);
        }else{
            $data= new Pengumuman();
        }
        $data->perihal=Yii::$app->request->post('perihal', '');
        $data->isi=Yii::$app->request->post('isi', '');
        $data->tgl_pengumuman=Yii::$app->request->post('tgl_pengumuman', '');
        try{
            $data->save();
            return "
            <div class='alert alert-success'>Data berhasil disimpan</div>
            <script> reloadData(); closeModal(1500); </script>";
        }catch (Exception $e){
            return "
            <div class='alert alert-danger'>Data gagal disimpan</div>
            <script> reloadData(); closeModal(1500); </script>";
        }
    }
    public function  actionDelete(){
        $id = Yii::$app->request->post('id', 0);
        $data = Pengumuman::findOne($id);
        try {
            $data->delete();
            return "
            <div class='alert alert-success'>Data berhasil dihapus</div>
            <script> reloadData(); closeModal(1500); </script>";
        } catch (Exception $e) {
            return "
            <div class='alert alert-danger'>Terjadi kesalahan! Data gagal dihapus</div>";
        }
    }


}